language: cpp
compiler:
    - g++

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libpcre3 libpcre3-dev libgsasl7 libgsasl7-dev libgtest-dev
    - export CXX="g++-4.8"

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - autoconf
            - automake
            - libgsasl7-dev

script: ./bootstrap.sh && ./configure && make
