language: cpp
compiler:
    - g++
    - clang++

addons:
    apt:
        packages:
            - g++-4.8
            - autoconf
            - automake
            - autotools
            - openssh
            - libpcrecpp
            - libgsasl7-dev

script: ./bootstrap.sh && ./configure && make
